### ISSUE TITLE
Terminal Client

### ISSUE THREAD

**Issue by Miserlou** [jgillich/faststack#15]
I _love_ this product.

I think it'd be really cool if from my local machine I could:

`$ termbox ubuntu`

and then it would create the termbox and log me in over SSH. Then I could stop running Docker/VBox locally forever!

You could even show an ad in a login cowsay to offsay the cost:

```
 ________________________ 
< Use Termbox.io, Fool\! >
 ------------------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by jgillich** [comment]
The thing I first need to figure out is how to prevent abuse by automation. On the web, that is handled by Cloudflare and Recaptcha, but I don't think there's anything like that for the terminal. So I might just do paid accounts, in which case users could automate as much as they want.

**Comment by nyancat18** [comment]
@jgillich  
you should try to let
create ssh acounts with the browser (cloudfare+recaptcha)

after you get a text  
with your user
ip
and 
pass
