### ISSUE TITLE
Can't create box

### ISSUE THREAD

**Issue by Laerte** [jgillich/faststack#17]
After i launch box,  occours  this error in console of Google Chrome.

> index.js:2275 Uncaught TypeError: a.base.append is not a function(anonymous function) @ index.js:2275
> page.js:89 fullHeight 535 fullWidth 1600

Then i receive this page without terminal with the status "Reconnecting" forever.

![screencapture-termbox-io-term-pod-jevyuzrdre-1481377279420](https://cloud.githubusercontent.com/assets/5853172/21073710/9cdb15d0-becd-11e6-9a1d-0adf6072c3c3.png)

**Comment by jgillich** [comment]
Hmm, I thought I fixed that in dfb50ce039ec08485dfca702d8ed3d18797d08a5, apparently not. However, I can not reproduce it and I don't see anything wrong with the code.
