### ISSUE TITLE
Can't run docker from within terbox.

### ISSUE THREAD

**Issue by r-o-g** [jgillich/faststack#24]
I'm trying to run docker from within the termbox on termbox.io, but keep hitting a wall with Aufs not being supported by the kernel. Could you please look into this? Thanks!

**Comment by jgillich** [comment]
Boxes are containers themselves, the Linux kernel they run on is very lightweight and probably lacks all of the overlay file system modules Docker needs.

But: we are using a Docker-compatible run-time, which means we can directly run Docker images. I've opened #25 to track this.
