### ISSUE TITLE
Error 522. Can't access to termbox.io

### ISSUE THREAD

**Issue by GTRONICK** [jgillich/faststack#30]
Since yesterday, I'm trying to connect to the web application at [Termbox](https://termbox.io), but the service seems to be down. Error 522 is reported in the browser.

Looking for it I found: [Error 522](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out).

Best regards.

**Comment by GTRONICK** [comment]
Today, I was able to load the page, however, when trying to launch a session like Ubuntu, the status shows "connecting", and flash to "connected" for few milliseconds, then, returns to "connecting".

**Comment by Pokaia** [comment]
Seeing this also.

**Comment by jgillich** [comment]
I had to wipe the hyperd data dir to get it working again, unfortunately its error log isn't really helpful. Thinking about moving to the master version since they don't seem to be backporting fixes.
