### ISSUE TITLE
Cannot copy and paste on termbox.io website

### ISSUE THREAD

**Issue by likeadragonmaid** [jgillich/faststack#45]
I am unable to copy and paste in terminal box in the website, isn't it a basic feature?
Please add it.

**Comment by likeadragonmaid** [comment]
I found that it works with ctrl+shift+c and ctrl+shift+v on chromium, but not on firefox...

**Comment by jgillich** [comment]
That's a Firefox limitation, unfortunately we can't do anything about that.
